//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverView_WebServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password=systex.6214;Persist Security Info=True;User ID=sa;Initial Catalog=CRMDem" +
            "o_MSCRM;Data Source=10.10.53.205")]
        public string SQLConnectStr {
            get {
                return ((string)(this["SQLConnectStr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=10.10.53.215;Database=FDIP;User ID=SGTP;password=systex.6214;Trusted_Conne" +
            "ction=False;Asynchronous Processing=true;Failover Partner=10.10.56.242;")]
        public string DB_FDIP {
            get {
                return ((string)(this["DB_FDIP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=10.10.53.215;Database=FDIP_MonitorSystem;User ID=SGTP;password=systex.6214" +
            ";Trusted_Connection=False;Asynchronous Processing=true;Failover Partner=10.10.56" +
            ".242;")]
        public string DB_SYSDEF {
            get {
                return ((string)(this["DB_SYSDEF"]));
            }
        }
    }
}
